server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mirae?serverTimezone=Asia/Seoul
    username: mirae
    password: mirae1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /template/
      suffix: ./mustache


  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 251592516648-067uamvtrqirvuovgken2hl2qdlnv4vg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 877259743322267
            client-secret: c4b8679102dfa662aeb89bcfdd346331
            scope:
              - email
              - public_profile
          naver:
            client_id: bDRtfMX2vo0axdEZiWZm
            client-secret: LIpnqqxjij
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response