server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mirae?serverTimezone=Asia/Seoul
    username: mirae
    password: mirae1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /template/
      suffix: ./mustache


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true